

services:
  volurya_postgres:
    image: postgres:16
    container_name: volurya_postgres
    environment:
      POSTGRES_USER: volurya
      POSTGRES_PASSWORD: volurya
      POSTGRES_DB: volurya_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  volurya:
    container_name: volurya
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - volurya_postgres
    volumes:
      - ./:/go/src/app   # monta o código do host
    environment:
      JWT_SECRET: volurya-secret-key-super-forte-aqui  
    
      POSTGRES_HOST: volurya_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: volurya
      POSTGRES_PASSWORD: volurya
      POSTGRES_DB: volurya_db

volumes:
  pgdata:
