

services:
  volurya_postgres:
    image: postgres:16
    container_name: volurya_postgres
    environment:
      POSTGRES_USER: volurya
      POSTGRES_PASSWORD: volurya
      POSTGRES_DB: volurya_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  volurya:
    container_name: volurya
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - volurya_postgres
    volumes:
      - ./:/go/src/app   # monta o código do host
    environment:
      APP_ENV: ${APP_ENV}
      ACCESS_TOKEN_DURATION_MINUTES: ${ACCESS_TOKEN_DURATION_MINUTES}
      REFRESH_TOKEN_DURATION_DAYS: ${REFRESH_TOKEN_DURATION_DAYS}
      PAGSEGURO_EMAIL: iagobarrosgomes2112@gmail.com
      PAGSEGURO_TOKEN: e97a3eef-3822-40ed-b7c7-8f1b14e2eccf8988860f4da393c9c841e9621e816428892c-ff1b-4606-9233-886cd85bf9e9
      PAGSEGURO_SANDBOX: true  # mude pra false em prod
      PAGSEGURO_WEBHOOK_URL: http://localhost:8080/api/webhook
      JWT_SECRET: volurya-secret-key-super-forte-aqui  
    
      POSTGRES_HOST: volurya_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: volurya
      POSTGRES_PASSWORD: volurya
      POSTGRES_DB: volurya_db

  prometheus:
    image: prom/prometheus:latest
    container_name: volurya_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: volurya_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus

volumes:
  pgdata:
  prometheus_data:
  grafana_data:
