

services:
  postgres_test:
    image: postgres:16
    container_name: volurya_postgres_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: volurya_test
    ports:
      - "5433:5432"
    volumes:
      - volurya_test_data:/var/lib/postgresql/data

volumes:
  volurya_test_data:
